version: 0.2

phases:
  install:
    runtime-versions:
      java: corretto8
    commands:
      - echo Entered the install phase...
      - curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
      - apt-get update -y
      - apt-get install -y gradle
    finally:
      - echo This always runs even if the update or install command fails

  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - gradle build
    finally:
      - echo This always runs even if the install command fails
  post_build:
    commands:
      - echo Entered the post_build phase...
      - echo Build completed on `date`


artifacts:
  files:
    - build/libs/order-service-0.0.1-SNAPSHOT.jar
  discard-paths: yes

